application:
  version: 1.0.0
spring:

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: kkt971229@gmail.com #앱 비밀번호 발급받은 google 계정
    password: hwwxqiwjehymlhwy    #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  # multipart form data 전송방식 사용시 , 데이터 크기의 제약 사항
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-konkuk.cxep7ikjimy9.ap-northeast-2.rds.amazonaws.com:3306/eleven_db?serverTimezone=Asia/Seoul
    username: admin
    password: konkukpw2022

  jpa:
    open-in-view: true # open session in view 를 true로 설정하므로써 -> 트랜잭션 범위 내에서만 SQL이 나가게 된다. -> 즉 SQL이 남발하여 나가는 상황을 막게 됨
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # batch size를 설정하므로써 -> LAZY LOADING 시 여러 연관된 엔티티들을 IN 절로 한꺼번에 가져오게 됨 -> 성능 향상을 위함

server:
  port: 3000  # 3000번 포트로 실행

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  password: AA993906-44D7-47B5-87B0-1330C290CC0D



